#! /bin/bash

set -e

echo "restore configuration"
for i in $CONFIG; do
    rsync -a --ignore-existing $i.bak/ $i/
    chown -R www-data.www-data $i
done


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"