FROM slpcat/python:3.10.11-ubuntu2004
#https://pytorch.org/get-started/previous-versions/
RUN pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117

