FROM ubuntu:24.04 as build

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y curl make gcc

RUN curl -s -L https://github.com/ncopa/su-exec/archive/v0.2.tar.gz | tar zx -C /opt/ \
    && mv /opt/su-exec* /opt/su-exec \
    && cd /opt/su-exec \
    && make

####################################
FROM ubuntu:24.04

# Deploy ubuntu container without minimized packages
RUN yes | unminimize

ENV \
    TERM="xterm-256color" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8"

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

# Set timezone and locales
RUN \
    apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get install -yq apt-utils dialog tzdata language-pack-zh-hans language-pack-zh-hans-base \
    && echo "$LANG UTF-8" > /etc/locale.gen \
    && update-locale LANG=$LANG \
    && locale-gen $LANG zh_CN.UTF-8

#RUN locale-gen $LANG \
#    && echo "LC_ALL=$LANG" > /etc/default/locale \
#    && echo "LANG=$LANG" >> /etc/default/locale

RUN \
    userdel -r ubuntu \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y runit \
    && ln -sf /usr/sbin/runit /sbin/init

# For slim:
#   --build-arg ADDITIONAL_APT_GET_OPTS=--no-install-recommends
ARG ADDITIONAL_APT_GET_OPTS=""

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y $ADDITIONAL_APT_GET_OPTS \
      vim-tiny \
      wget     \
      dbus-x11 \
      fonts-noto-cjk \
      fonts-noto-color-emoji \
      fonts-symbola \
      ttf-ancient-fonts \
      fcitx5 \
      fcitx5-rime \
      fcitx5-table-emoji \
      fcitx5-chinese-addons \
      fcitx5-material-color \
      #im-switch \
      lxde-core \
      #lxpanel can not work
      icewm \
      gexec \
      lxterminal \
      xfe \
      sudo \
      tzdata \
      xorg \
      xorgxrdp \
      xrdp \
    && apt-get remove --purge -y xscreensaver* network-manager && apt-get autoremove --purge -y

COPY --from=build \
    /opt/su-exec/su-exec /usr/sbin/su-exec

# Set default vars
ENV DEFAULT_USER=developer \
    DEFAULT_PASSWD=xrdppasswd

# Set sudoers for any user
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/ALL

# Change permission so that non-root user can add users and groups
RUN chmod u+s /usr/sbin/useradd \
    && chmod u+s /usr/sbin/groupadd

RUN \
    apt-get install -y fluxbox fbpager fbautostart xfonts-terminus-oblique yudit-doc yudit \
            xcompmgr dmenu lxappearance nitrogen \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#generates an applications menu for Fluxbox using the freedesktop.org (XDG) standard.
RUN \
    wget https://github.com/confluence/fbxdgmenu/raw/refs/heads/master/fbxdgmenu.py \
    && chmod +x fbxdgmenu.py && mv fbxdgmenu.py /usr/local/bin/

# Setup
RUN { \
        echo 'if [[ -d /run/user/$(id -u) ]]; then'; \
        echo '  export XDG_RUNTIME_DIR=/run/user/$(id -u)'; \
        echo 'fi'; \
        echo 'exec dbus-run-session -- icewm-session'; \
    } > /etc/skel/.xsession \
    && update-alternatives --set x-terminal-emulator /usr/bin/lxterminal \
    && install -o root -g xrdp -m 2775 -d /var/run/xrdp \
    && install -o root -g xrdp -m 3777 -d /var/run/xrdp/sockdir \
    && install -o root -g root -m 0755 -d /var/run/dbus \
    && install -o root -g root -m 0644 /dev/null /etc/securetty \
    && usermod -aG ssl-cert xrdp \
    && sed -i 's|\[Session\]|&\npolkit/command=|' /etc/xdg/lxsession/LXDE/desktop.conf \
    && usermod -aG ssl-cert xrdp \
    && ln -s /usr/share/lxde/wallpapers/lxde_blue.jpg /etc/alternatives/desktop-background

COPY rootfs/ /
# Disable unavailable features
RUN sed -i 's|.*pam_systemd.so|#&|g' /etc/pam.d/common-session \
#    && rm -f /etc/xdg/autostart/geoclue-demo-agent.desktop \
#    && rm -f /etc/xdg/autostart/at-spi-dbus-bus.desktop \
#    && rm -f /etc/xdg/autostart/parcellite-startup.desktop \
#    && rm -f /etc/xdg/autostart/nm-applet.desktop \
    && rm -f /etc/xdg/autostart/org.gnome.Evolution-alarm-notify.desktop \
    && rm -f /etc/xdg/autostart/org.gnome.SettingsDaemon.Power.desktop

# runit config
RUN \
    ln -s /etc/sv/dbus /etc/service/dbus && \
    ln -s /etc/sv/xrdp /etc/service/xrdp && \
    ln -s /etc/sv/xrdp-sesman /etc/service/xrdp-sesman

# Expose RDP port
EXPOSE 3389

# Copy entrypoint script
COPY runit-entrypoint.sh /usr/local/bin/
RUN \
    chmod +x /etc/sv/*/run \
    && chmod +x /usr/local/bin/runit-entrypoint.sh
ENTRYPOINT ["runit-entrypoint.sh"]
