FROM slpcat/docker-ubuntu-lxde:24.04-xrdp_developer

#kubectl-ai
RUN \
    wget https://github.com/GoogleCloudPlatform/kubectl-ai/releases/download/v0.0.29/kubectl-ai_Linux_x86_64.tar.gz \
    && tar -xzf kubectl-ai_Linux_x86_64.tar.gz \
    && chmod +x kubectl-ai \
    && mv kubectl-ai /usr/local/bin \
    && rm -f kubectl-ai_Linux_x86_64.tar.gz

#k8sgpt
RUN \
    wget https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.27/k8sgpt_amd64.deb \
    && apt-get install -y ./k8sgpt_amd64.deb && rm -f k8sgpt_amd64.deb

#claude
#openai codex
#gemini
#cline
#opencode
#n8n
#dash0/Agent0 https://www.dash0.com/
#Void开源AI代码编辑器 https://voideditor.com/ paused
#
#splunk ai
#elastic ai
# https://www.moxo.com/
#Operationalize every process.
#Blend AI and human judgment
#Adapt in real time.

#AI meets human judgement
#Cross-department orchestration
#From diagrams to execution
#Visibility and governance


#trae ai编程工具 https://www.trae.ai/

#Qoder, Agentic Coding Platform for Real Software
#https://qoder.com/
RUN \
    wget https://download.qoder.com/release/latest/qoder_amd64.deb \
    && apt-get install -y ./qoder_amd64.deb && rm -f qoder_amd64.deb

#
#dify
#ollama
#vLLM 推理服务
#腾讯ima
#Cherry Studio

#Gnoppix AI Linux
#AI Email Support
#AI Vulnerability Scanning
#AI Searching
#AI Web Chat Agent
#AI HR Agent
#AI Webscraper

# Install AI coding/Vibe coding tools
# Claude Code , Cursor CLI, CodeX,Gemini CLI,cline
    #curl https://cursor.com/install -fsS | bash \
    #mv $HOME/.local/bin/cursor-agent /usr/local/bin/ \
RUN \
    npm install -g @anthropic-ai/claude-code && \
    npm install -g @openai/codex && \
    npm install -g @google/gemini-cli && \
    npm install -g cline && \
    rm -rf /root/.npm

# zed.dev
RUN \
    flatpak install -y flathub dev.zed.Zed
#    curl -f https://zed.dev/install.sh | sh
#RUN \
#    curl -sS https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/debian.griffo.io.gpg && \
#    echo "deb https://debian.griffo.io/apt $(lsb_release -sc 2>/dev/null) main" | tee /etc/apt/sources.list.d/debian.griffo.io.list && \
#    apt-get update && apt-get install -y zig ghostty lazygit yazi eza uv fzf zoxide bun tigerbeetle

#Cursor is the best way to code with AI.
RUN \
    wget https://downloads.cursor.com/production/618c607a249dd7fd2ffc662c6531143833bebd44/linux/x64/deb/amd64/deb/cursor_2.4.22_amd64.deb \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ./cursor_2.4.22_amd64.deb && rm -f cursor_2.4.22_amd64.deb

#cd /tmp
#curl -L "https://www.cursor.com/api/download?platform=linux-x64&releaseTrack=stable" | jq -r '.downloadUrl' | xargs curl -L -o cursor.appimage
#sudo mv cursor.appimage /opt/cursor.appimage
#sudo chmod +x /opt/cursor.appimage
#sudo apt install -y fuse3
#sudo apt install -y libfuse2t64
#
#DESKTOP_FILE="/usr/share/applications/cursor.desktop"
#
#sudo bash -c "cat > $DESKTOP_FILE" <<EOL
#[Desktop Entry]
#Name=Cursor
#Comment=AI-powered code editor
#Exec=/opt/cursor.appimage --no-sandbox
#Icon=/home/$USER/.local/share/omakub/applications/icons/cursor.png
#Type=Application
#Categories=Development;IDE;
#EOL

#if [ -f "$DESKTOP_FILE" ]; then
#	echo "cursor.desktop created successfully"
#else
#	echo "Failed to create cursor.desktop"
#fi

# windsurf The best AI for Coding
RUN \
    curl -fsSL "https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/windsurf.gpg" | gpg --dearmor -o /usr/share/keyrings/windsurf-stable-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/windsurf-stable-archive-keyring.gpg arch=amd64] https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/apt stable main" | tee /etc/apt/sources.list.d/windsurf.list >/dev/null \
    && apt-get update && apt-get install -y windsurf

# Warp Terminal
RUN \
    wget https://releases.warp.dev/stable/v0.2026.01.21.08.14.stable_03/warp-terminal_0.2026.01.21.08.14.stable.03_amd64.deb && \
    apt-get install -y ./warp-terminal_0.2026.01.21.08.14.stable.03_amd64.deb && rm -f warp-terminal_0.2026.01.21.08.14.stable.03_amd64.deb

# Wave Termianl

# Clawdbot/moltbot
#https://github.com/moltbot/moltbot
#bytebot
#https://github.com/bytebot-ai/bytebot.git
#everywhere 桌面智能
#https://github.com/DearVa/Everywhere
#open agent
#omniparser
#os-copilot
#appagent
#腾讯youtu-agent
#字节ui-tars-desktop
#ssh-mcp
#obsidian 
#微软magentic ui
#iflow
#turix cua
#sima打游戏
#agent browser
#ghosty + claude
#newwelle
#cowork

