#kubectl-ai

#claude
#openai codex
#gemini
#cline
#opencode
#n8n
#Void开源AI代码编辑器 https://voideditor.com/ paused
#

#trae ai编程工具
#dify
#ollama
#vLLM 推理服务
#腾讯ima
#Cherry Studio

#Gnoppix AI Linux
#AI Email Support
#AI Vulnerability Scanning
#AI Searching
#AI Web Chat Agent
#AI HR Agent
#AI Webscraper

# Install AI coding/Vibe coding tools
# Claude Code , Cursor CLI, CodeX,Gemini CLI,cline
    #curl https://cursor.com/install -fsS | bash \
    #mv $HOME/.local/bin/cursor-agent /usr/local/bin/ \
RUN \
    npm install -g @anthropic-ai/claude-code && \
    npm install -g @openai/codex && \
    npm install -g @google/gemini-cli && \
    npm install -g cline

# zed.dev
#    curl -f https://zed.dev/install.sh | sh
RUN \
    curl -sS https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/debian.griffo.io.gpg && \
    echo "deb https://debian.griffo.io/apt $(lsb_release -sc 2>/dev/null) main" | tee /etc/apt/sources.list.d/debian.griffo.io.list && \
    apt-get update && apt-get install -y zig ghostty lazygit yazi eza uv fzf zoxide bun tigerbeetle
