FROM slpcat/docker-ubuntu-lxde:24.04-xrdp_audio

RUN apt-get update -y             \
    && apt-get upgrade -y         \
    && apt-get install -y         \
       apt-transport-https        \
       binutils                   \
       ethtool                    \
       htop                       \
       iotop                      \
       iftop                      \
       ethtool                    \
       vim-tiny                   \
       iproute2                   \
       wget                       \
       telnet                     \
       less                       \
       bison                      \
       ca-certificates            \
       net-tools                  \
       procps                     \
       curl                       \
       rsync                      \
       gnupg-agent                \
       software-properties-common \
       bzip2                \
       sudo                 \
       git                  \
       iptables             \
       vim                  \
       tmux                 \
       jq                   \
       yq                   \
       openssh-client       \
       unzip                \
       zip                  \
       groff                \
       #snoopy               \
       ttf-wqy-microhei     \
       ttf-wqy-zenhei       \
       xfonts-wqy           \
       clamav               \
       clamav-freshclam     \
       python3              \
       python3-pip          \
       python3-all-venv     \
       python3-pytest       \
       pipx                 \
       xvfb

#install docker-ce
#RUN \
#    curl -fsSL http://mirrors.aliyun.com/docker-ce/linux/debian/gpg | apt-key add - && \
#    echo 'deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/debian bullseye stable' > /etc/apt/sources.list.d/docker-ce.list && \
#    apt-get update -y &&\
#    apt-get install -y docker-ce

# Add Docker's official GPG key:
RUN \
    apt-get update && \
    apt-get install -y ca-certificates curl gnupg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \

# Add the repository to Apt sources:
    echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
       tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Install Google Chrome and driver
RUN \
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmour -o /usr/share/keyrings/chrome-keyring.gpg && \
    sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list' && \
    apt-get update && apt-get install -y google-chrome-stable && \
    wget https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/linux64/chromedriver-linux64.zip && \
    unzip chromedriver-linux64.zip && \
    mv chromedriver-linux64/chromedriver /usr/local/bin && \
    chmod +x /usr/local/bin/chromedriver && \
    wget https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/linux64/chrome-headless-shell-linux64.zip && \
    unzip chrome-headless-shell-linux64.zip && \
    mv chrome-headless-shell-linux64 /opt/google/ && \
    ln -s /opt/google/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chrome-headless-shell && \
    rm -rf chromedriver* chrome-headless-shell*

# Install Mozilla Firefox and driver
COPY install-firefox.sh /tmp/install-firefox.sh
RUN \
    bash /tmp/install-firefox.sh && rm -f /tmp/install-firefox.sh && \
    wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz && \
    tar zxf geckodriver-v0.36.0-linux64.tar.gz && \
    mv geckodriver /usr/local/bin/ && \
    rm -rf geckodriver*

# Install Microsoft Edge and driver
RUN \
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list && \
    apt-get update && apt-get install -y microsoft-edge-stable && \
    wget https://msedgedriver.microsoft.com/143.0.3650.96/edgedriver_linux64.zip && \
    unzip edgedriver_linux64.zip && \
    mv msedgedriver /usr/local/bin && \
    rm -rf edgedriver* Driver_Notes

# Install nodejs lts
RUN \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -  && \
    apt-get update && apt-get install -y nodejs

# Install selenium-side-runner
# Install AI coding/Vibe coding tools
# Claude Code , Cursor CLI, CodeX,Gemini CLI,cline
    #curl https://cursor.com/install -fsS | bash \
    #mv $HOME/.local/bin/cursor-agent /usr/local/bin/ \
RUN \
    npm install -g selenium-side-runner && \
    npm install -g @anthropic-ai/claude-code && \
    npm install -g @openai/codex && \
    npm install -g @google/gemini-cli && \
    npm install -g cline

#install ansible
RUN \
    apt-get install -y ansible ansible-mitogen

# Environment variables substitution for Go
RUN \
    curl -L https://github.com/a8m/envsubst/releases/download/v1.4.3/envsubst-`uname -s`-`uname -m` -o envsubst && \
    chmod +x envsubst && \
    mv envsubst /usr/local/bin

#kubectl
RUN \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/

#helm
ARG VERIFY_CHECKSUM=false
#RUN \
#    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
#    && bash get_helm.sh \
#    && rm get_helm.sh
RUN \
    curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list &&\
    apt-get update && \
    apt-get install -y helm

#istioctl
ARG ISTIO_VERSION=1.24.0
RUN \
    curl -L https://istio.io/downloadIstio | sh - \
    && mv istio-${ISTIO_VERSION}/bin/istioctl /usr/local/bin \
    && rm -rf  istio-${ISTIO_VERSION}

RUN \
    wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list \
    && apt-get update && apt-get install -y packer terraform consul

#aliyun-cli
ARG ALIYUN_CLI_VERSION=3.0.60
RUN \
    wget https://aliyuncli.alicdn.com/aliyun-cli-linux-${ALIYUN_CLI_VERSION}-amd64.tgz \
    && tar -zxvf aliyun-cli-linux-${ALIYUN_CLI_VERSION}-amd64.tgz \
    && mv aliyun /usr/local/bin \
    && rm aliyun-cli-linux-${ALIYUN_CLI_VERSION}-amd64.tgz

#awscli
RUN \
    wget https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip \
    && unzip awscli-exe-linux-x86_64.zip \
    && ./aws/install \
    && rm -rf aws*

#grype scanner
RUN \
    curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

# clash-verge-rev
RUN \
    wget https://github.com/clash-verge-rev/clash-verge-rev/releases/download/autobuild/Clash.Verge_2.4.5+autobuild.0113.66e9851_amd64.deb \
    && apt-get install -y ./Clash.Verge_2.4.5+autobuild.0113.66e9851_amd64.deb \
    && rm -rf Clash.Verge*

# redis-ui
RUN \
    wget https://github.com/patrikx3/redis-ui/releases/download/v2025.10.110/p3x-redis-ui_2025.10.110_amd64.deb && \
    apt-get install -y ./p3x-redis-ui_2025.10.110_amd64.deb &&  rm -f p3x-redis-ui_2025.10.110_amd64.deb

# mongodb compass
RUN \
    wget https://downloads.mongodb.com/compass/mongodb-compass_1.48.2_amd64.deb && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y ./mongodb-compass_1.48.2_amd64.deb && rm -f mongodb-compass_1.48.2_amd64.deb

# dbeaver
RUN \
    wget -O /usr/share/keyrings/dbeaver.gpg.key https://dbeaver.io/debs/dbeaver.gpg.key && \
    echo "deb [signed-by=/usr/share/keyrings/dbeaver.gpg.key] https://dbeaver.io/debs/dbeaver-ce /" | tee /etc/apt/sources.list.d/dbeaver.list && \
    apt-get update && sudo apt-get install -y dbeaver-ce

## VSCode
RUN \
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/microsoft-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list \
    && apt-get update \
    && apt-get install -y code \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

# kodi
#RUN \
#    add-apt-repository ppa:team-xbmc/ppa && \
#    apt-get update && apt-get install -y  kodi

# OBS Studio 
RUN \
    add-apt-repository ppa:obsproject/obs-studio && \
    apt-get update && apt-get install -y obs-studio
