apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: my-k0s-cluster
  user: admin
spec:
  hosts:

  - role: controller+worker
    hostname: k0s-node001
    environment:
      HTTP_PROXY: 10.0.0.1:443
    installFlags:
    - --debug
    ssh:
      address: 10.0.0.1
      user: root
      port: 22
    #  keyPath: ~/.ssh/id_rsa
    #privateInterface: eth0
    #privateAddress: 10.0.0.1
    dataDir: /var/lib/k0s
    #k0sDownloadURL: https://files.example.com/k0s%20files/k0s-%v-%p%x
    # 从本地 上传 k0s bin 文件，不要在目标机器下载
    #uploadBinary: true
    #k0sBinaryPath: /path/tmp/k0s
    # files:
    #   - name: bundle-file
    #     src: /root/k0s-airgap-bundle-v1.33.1+k0s.0-amd64
    #     dstDir: /var/lib/k0s/images/
    #     perm: 0755

  - role: controller+worker
    hostname: k0s-node002
    environment:
      HTTP_PROXY: 10.0.0.1:443
    installFlags:
    - --debug
    ssh:
      address: 10.0.0.2
      user: root
      port: 22
    #  keyPath: ~/.ssh/id_rsa
    #privateInterface: eth0
    #privateAddress: 10.0.0.1
    dataDir: /var/lib/k0s
    #k0sDownloadURL: https://files.example.com/k0s%20files/k0s-%v-%p%x
    # 从本地 上传 k0s bin 文件，不要在目标机器下载
    #uploadBinary: true
    #k0sBinaryPath: /path/tmp/k0s
    # files:
    #   - name: bundle-file
    #     src: /root/k0s-airgap-bundle-v1.33.1+k0s.0-amd64
    #     dstDir: /var/lib/k0s/images/
    #     perm: 0755

  - role: controller+worker
    hostname: k0s-node003
    environment:
      HTTP_PROXY: 10.0.0.1:443
    installFlags:
    - --debug
    ssh:
      address: 10.0.0.3
      user: root
      port: 22
    #  keyPath: ~/.ssh/id_rsa
    #privateInterface: eth0
    #privateAddress: 10.0.0.1
    dataDir: /var/lib/k0s
    #k0sDownloadURL: https://files.example.com/k0s%20files/k0s-%v-%p%x
    # 从本地 上传 k0s bin 文件，不要在目标机器下载
    #uploadBinary: true
    #k0sBinaryPath: /path/tmp/k0s
    # files:
    #   - name: bundle-file
    #     src: /root/k0s-airgap-bundle-v1.33.1+k0s.0-amd64
    #     dstDir: /var/lib/k0s/images/
    #     perm: 0755

  - role: worker
    installFlags:
    - --debug
    ssh:
      address: 10.0.0.5
      user: root
      port: 22

  k0s:
    version: 1.33.1+k0s.0
    args:
      - "--disable-components=kube-state-metrics"
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          #externalAddress: <load balancer public ip address>
          #sans:
          #- <load balancer public ip address>
        images:
          #calico:
          #  cni:
          #    image: docker.io/calico/cni
          #    version: v3.18.1
          #  kubecontrollers:
          #    image: docker.io/calico/kube-controllers
          #    version: v3.18.1
          #  node:
          #    image: docker.io/calico/node
          #    version: v3.18.1
          coredns:
            image: quay.io/k0sproject/coredns
            version: 1.12.1
          default_pull_policy: IfNotPresent
          #default_pull_policy: Never
          #konnectivity:
          #  image: slpcat/proxy-agent
          #  version: v0.0.24
          kubeproxy:
            image: quay.io/k0sproject/kube-proxy
            version: v1.33.1
          kuberouter:
            cni:
              image: quay.io/k0sproject/kube-router
              version: v2.5.0-iptables1.8.11-0
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 1.7.1-k0s.0
          metricsserver:
            image: quay.io/k0sproject/metrics-server
            version: v0.7.2-0
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          #controlPlaneLoadBalancing:
          #  enabled: true
          #  type: Keepalived
          #  keepalived:
          #    vrrpInstances:
          #    - virtualIPs: ["192.168.122.200/24"]
          #      authPass: Example
          nodeLocalLoadBalancing: # optional, but CPLB will often be used with NLLB.
            enabled: true
            type: EnvoyProxy
          clusterDomain: cluster.local
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
          dualStack:
            enabled: true
            IPv6podCIDR: fd00::/108
            IPv6serviceCIDR: fd01::/108
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type:
            etcd:
              ca:
                expiresAfter: 87600h
                certificatesExpireAfter: 87600h
              #extraArgs:
          #type: kine
          #  kine:
          #    dataSource: "sqlite:///var/lib/k0s/db/state.db?more=rwc&_journal=WAL&cache=shared"
        telemetry:
          enabled: false

  options:
    wait:
      enabled: true
    drain:
      enabled: true
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
    concurrency:
      limit: 30
      uploads: 5
