variable "tc_secret_id" {
  type    = string
  default = "${env("TENCENTCLOUD_ACCESS_KEY")}"
}

variable "tc_secret_key" {
  type    = string
  default = "${env("TENCENTCLOUD_SECRET_KEY")}"
}

source "tencentcloud-cvm" "autogenerated_1" {
  associate_public_ip_address = true
  disk_type                   = "CLOUD_PREMIUM"
  image_name                  = "nginx-service-v1"
  instance_type               = "S3.MEDIUM4"
  internet_max_bandwidth_out  = 2
  region                      = "ap-chengdu"
  secret_id                   = "${var.tc_secret_id}"
  secret_key                  = "${var.tc_secret_key}"
  security_group_id           = "sg-5mn1s3xh"
  source_image_id             = "img-oikl1tzv"
  ssh_username                = "root"
  subnet_id                   = "subnet-h5mz612h"
  vpc_id                      = "vpc-mz4iixkm"
  zone                        = "ap-chengdu-1"
}

build {
  sources = ["source.tencentcloud-cvm.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm",
      "yum install -y nginx",
      "systemctl enable nginx",
      "systemctl start nginx"
    ]
  }
}
