#!/bin/bash

# Copyright (c) 2019 FEROX YT EIRL, www.ferox.yt <devops@ferox.yt>
# Copyright (c) 2019 Jérémy WALTHER <jeremy.walther@golflima.net>
# See <https://github.com/frxyt/docker-xrdp> for details.

docker build \
    --build-arg DOCKER_TAG=${DOCKER_TAG} \
    --build-arg SOURCE_BRANCH=${SOURCE_BRANCH} \
    --build-arg SOURCE_COMMIT=${SOURCE_COMMIT} \
    -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .