
source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "0bfc2293-4d69-49b5-83f7-bf0d60d20c45"
  client_secret                     = "G3.6ytCh44Kcla~_JRPBDLkzsXLOa3edDL"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "16.04-LTS"
  location                          = "East US"
  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "myPackerImages"
  os_type                           = "Linux"
  subscription_id                   = "b162117f-53fa-4f42-8c77-6a65ca966c40"
  tenant_id                         = "c3fd441d-b8ad-487e-aa27-453079018fca"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = [
      "apt-get update",
      "apt-get upgrade -y",
      "apt-get -y install nginx",
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ]
    inline_shebang  = "/bin/sh -x"
  }

}
