---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: logging
    version: target
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-logging
data:
  catalog-logging.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "logging"
        version: "target"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "logging"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "ServiceAccount"
      metadata:
        annotations: {}
        finalizers: []
        labels:
          provider: "fabric8"
          project: "fluentd"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "fluentd"
        ownerReferences: []
      imagePullSecrets: []
      secrets: []
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          expose: "true"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "elasticsearch"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "http"
          port: 9200
          protocol: "TCP"
          targetPort: 9200
        selector:
          project: "elasticsearch"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "elasticsearch-masters"
        ownerReferences: []
      spec:
        clusterIP: "None"
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "discovery"
          port: 9300
          protocol: "TCP"
          targetPort: 9300
        selector:
          project: "elasticsearch"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/app-menu: "management"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          expose: "true"
          project: "kibana"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "kibana"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "http"
          port: 80
          protocol: "TCP"
          targetPort: 5601
        selector:
          project: "kibana"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
      metadata:
        annotations:
        finalizers: []
        labels:
          provider: "fabric8"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "es-data"
        ownerReferences: []
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          limits: {}
          requests:
            storage: "10Gi"
    - apiVersion: "extensions/v1beta1"
      kind: "DaemonSet"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/fluentd/src/main/fabric8/icon.png"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "fluentd"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "fluentd"
        ownerReferences: []
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/scrape: "true"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "fluentd"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "ELASTICSEARCH_HOST"
                value: "elasticsearch"
              - name: "ELASTICSEARCH_PORT"
                value: "9200"
              image: "fabric8/fluentd-kubernetes:v1.19"
              name: "fluentd"
              ports:
              - containerPort: 24231
                name: "scrape"
              resources:
                limits:
                  cpu: "100m"
                requests: {}
              securityContext:
                privileged: true
              volumeMounts:
              - mountPath: "/var/log"
                name: "varlog"
              - mountPath: "/var/lib/docker/containers"
                name: "defaultdocker"
                readOnly: true
              - mountPath: "/mnt/ephemeral/docker/containers"
                name: "awsdocker"
                readOnly: true
              - mountPath: "/mnt/sda1/var/lib/docker/containers"
                name: "minikubedocker"
                readOnly: true
            imagePullSecrets: []
            nodeSelector: {}
            serviceAccountName: "fluentd"
            volumes:
            - hostPath:
                path: "/var/log"
              name: "varlog"
            - hostPath:
                path: "/var/lib/docker/containers"
              name: "defaultdocker"
            - hostPath:
                path: "/mnt/ephemeral/docker/containers"
              name: "awsdocker"
            - hostPath:
                path: "/mnt/sda1/var/lib/docker/containers"
              name: "minikubedocker"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=elasticsearch&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "elasticsearch"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            project: "elasticsearch"
            provider: "fabric8"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=elasticsearch&var-version=2.2.311"
              pod.alpha.kubernetes.io/init-containers: "[{\"image\":\"busybox\",\"imagePullPolicy\"\
                :\"IfNotPresent\",\"name\":\"init\",\"command\":[\"chmod\",\"777\",\"\
                /usr/share/elasticsearch/data\"],\"volumeMounts\":[{\"mountPath\":\"/usr/share/elasticsearch/data\"\
                ,\"name\":\"data\"}]}]"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "elasticsearch"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "SERVICE"
                value: "elasticsearch-masters"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/elasticsearch-k8s:2.3.4"
              imagePullPolicy: "IfNotPresent"
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 9300
              name: "elasticsearch"
              ports: []
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/_template/logstash"
                  port: 9200
                initialDelaySeconds: 5
              securityContext:
                privileged: false
              volumeMounts:
              - mountPath: "/usr/share/elasticsearch/data"
                name: "data"
            - args: []
              command: []
              env: []
              image: "fabric8/elasticsearch-logstash-template:2.2.311"
              name: "logstash-template"
              ports: []
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - name: "data"
              persistentVolumeClaim:
                claimName: "es-data"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "kibana"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "kibana"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            project: "kibana"
            provider: "fabric8"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "kibana"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "ELASTICSEARCH_URL"
                value: "http://elasticsearch:9200"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/kibana4:v4.5.3"
              imagePullPolicy: "IfNotPresent"
              livenessProbe:
                initialDelaySeconds: 60
                tcpSocket:
                  port: 5601
              name: "kibana"
              ports: []
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/"
                  port: 5601
                initialDelaySeconds: 5
              securityContext:
                privileged: false
              volumeMounts: []
            - args: []
              command: []
              env:
              - name: "ELASTICSEARCH_URL"
                value: "http://elasticsearch:9200"
              image: "fabric8/kibana-config:2.2.311"
              name: "logstash-template"
              ports: []
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes: []
    parameters: []
