---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: elasticsearch
    version: 2.2.311
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-elasticsearch
data:
  catalog-elasticsearch.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "elasticsearch"
        version: "2.2.311"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "elasticsearch"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          expose: "true"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "elasticsearch"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "http"
          port: 9200
          protocol: "TCP"
          targetPort: 9200
        selector:
          project: "elasticsearch"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "elasticsearch-masters"
        ownerReferences: []
      spec:
        clusterIP: "None"
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "discovery"
          port: 9300
          protocol: "TCP"
          targetPort: 9300
        selector:
          project: "elasticsearch"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
      metadata:
        annotations:
        finalizers: []
        labels:
          provider: "fabric8"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "es-data"
        ownerReferences: []
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          limits: {}
          requests:
            storage: "10Gi"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=elasticsearch&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "elasticsearch"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "elasticsearch"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            project: "elasticsearch"
            provider: "fabric8"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=elasticsearch&var-version=2.2.311"
              pod.alpha.kubernetes.io/init-containers: "[{\"image\":\"busybox\",\"imagePullPolicy\"\
                :\"IfNotPresent\",\"name\":\"init\",\"command\":[\"chmod\",\"777\",\"\
                /usr/share/elasticsearch/data\"],\"volumeMounts\":[{\"mountPath\":\"/usr/share/elasticsearch/data\"\
                ,\"name\":\"data\"}]}]"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "elasticsearch"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "SERVICE"
                value: "elasticsearch-masters"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/elasticsearch-k8s:2.3.4"
              imagePullPolicy: "IfNotPresent"
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 9300
              name: "elasticsearch"
              ports: []
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/_template/logstash"
                  port: 9200
                initialDelaySeconds: 5
              securityContext:
                privileged: false
              volumeMounts:
              - mountPath: "/usr/share/elasticsearch/data"
                name: "data"
            - args: []
              command: []
              env: []
              image: "fabric8/elasticsearch-logstash-template:2.2.311"
              name: "logstash-template"
              ports: []
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - name: "data"
              persistentVolumeClaim:
                claimName: "es-data"
    parameters: []
