---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    name: hubot-slack
    project: chat-slack
    version: target
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-chat-slack
data:
  catalog-chat-slack.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        name: "hubot-slack"
        project: "chat-slack"
        version: "target"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "chat-slack"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/app-menu: "development"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          expose: "true"
          project: "hubot-slack"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 80
          targetPort: 8080
        selector:
          name: "hubot-slack"
          project: "hubot-slack"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-notifier"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-notifier"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "jolokia"
          port: 8778
          protocol: "TCP"
          targetPort: 8778
        selector:
          project: "hubot-notifier"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations:
          fabric8.hubot-notifier/summary: "Watches the OpenShift environment and notifies\
            \ Hubot of events such as builds completing or failing"
          description: "Watches the OpenShift environment and notifies Hubot of events\
            \ such as builds completing or failing."
          fabric8.hubot-notifier/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
          fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n\
            \    \"HUBOT_USERNAME\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The username for Hubot to login to the chat service\",\n      \"default\"\
            \ : \"fabric8\"\n    },\n    \"KUBERNETES_DNS_DOMAIN\" : {\n      \"type\"\
            \ : \"string\",\n      \"description\" : \"The DNS domain added to the serviceName.namespace.svc.\
            \ to make the DNS name\",\n      \"default\" : \"cluster.local\"\n    },\n\
            \    \"HUBOT_PASSWORD\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The password for Hubot to login to the chat service\",\n      \"default\"\
            \ : \"RedHat$1\"\n    }\n  }\n}"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-notifier"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-notifier"
        ownerReferences: []
      data:
        hubot-password: "RedHat$1"
        kubernetes-dns-domain: "cluster.local"
        hubot-username: "fabric8"
    - apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        annotations:
          fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n\
            \    \"HUBOT_SLACK_GRAFANA_HOST\" : {\n      \"type\" : \"string\",\n    \
            \  \"description\" : \"Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'\"\
            ,\n      \"default\" : \"http://grafana.default.svc.cluster.local\"\n    },\n\
            \    \"HUBOT_SLACK_GRAFANA_API_KEY\" : {\n      \"type\" : \"string\",\n \
            \     \"description\" : \"API key for a particular user\"\n    },\n    \"\
            HUBOT_JENKINS_URL\" : {\n      \"type\" : \"string\",\n      \"description\"\
            \ : \"The URL for the Jenkins CI server\",\n      \"default\" : \"http://jenkins.default.svc.cluster.local\"\
            \n    },\n    \"HUBOT_SLACK_TOKEN\" : {\n      \"type\" : \"string\",\n  \
            \    \"description\" : \"The token for Hubot to login to Slack\"\n    }\n\
            \  }\n}"
        finalizers: []
        labels:
          name: "hubot-slack"
          provider: "fabric8"
          project: "hubot-slack"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-slack"
        ownerReferences: []
      data:
        hubot-jenkins-url: "http://jenkins/"
        hubot-grafana-host: "http://grafana/"
        hubot-slack-token: ""
        hubot-grafana-api-key: ""
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-notifier&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "hubot-notifier"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-notifier"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "hubot-notifier"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-notifier&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "hubot-notifier"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "HUBOT_KUBERNETES_ROOM"
                value: "#fabric8_${namespace}"
              - name: "HUBOT_USERNAME"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-username"
                    name: "hubot-notifier"
              - name: "HUBOT_PASSWORD"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-password"
                    name: "hubot-notifier"
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              - name: "HUBOT_BUILD_ROOM"
                value: "#fabric8_${namespace}"
              image: "fabric8/hubot-notifier:2.2.311"
              imagePullPolicy: "IfNotPresent"
              name: "hubot-notifier"
              ports:
              - containerPort: 8778
                name: "jolokia"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: false
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            serviceAccountName: "fabric8"
            volumes: []
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2.311"
        finalizers: []
        labels:
          name: "hubot-slack"
          provider: "fabric8"
          project: "hubot-slack"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "hubot-slack"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            name: "hubot-slack"
            project: "hubot-slack"
            provider: "fabric8"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2.311"
            finalizers: []
            labels:
              name: "hubot-slack"
              provider: "fabric8"
              project: "hubot-slack"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            name: "hubot-slack"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "HUBOT_GRAFANA_API_KEY"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-grafana-api-key"
                    name: "hubot-slack"
              - name: "HUBOT_SLACK_TOKEN"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-slack-token"
                    name: "hubot-slack"
              - name: "HUBOT_GRAFANA_HOST"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-grafana-host"
                    name: "hubot-slack"
              - name: "HUBOT_JENKINS_URL"
                valueFrom:
                  configMapKeyRef:
                    key: "hubot-jenkins-url"
                    name: "hubot-slack"
              image: "fabric8/hubot-slack:2.2.311"
              name: "hubot-slack"
              ports:
              - containerPort: 8080
                name: "http"
                protocol: "TCP"
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes: []
    parameters: []
