---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/keycloak/src/main/fabric8/icon.svg
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: keycloak
    version: 2.2.311
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-keycloak
data:
  catalog-keycloak.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/keycloak/src/main/fabric8/icon.svg"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "keycloak"
        version: "2.2.311"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "keycloak"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/keycloak/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          expose: "true"
          provider: "fabric8"
          project: "keycloak"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "keycloak"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - name: "http"
          port: 80
          protocol: "TCP"
          targetPort: 8080
        selector:
          project: "keycloak"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
      metadata:
        annotations:
        finalizers: []
        labels:
          provider: "fabric8"
          project: "keycloak"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "keycloak-config"
        ownerReferences: []
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          limits: {}
          requests:
            storage: "1Gi"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
      metadata:
        annotations:
        finalizers: []
        labels:
          provider: "fabric8"
          project: "keycloak"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "keycloak-data"
        ownerReferences: []
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          limits: {}
          requests:
            storage: "1Gi"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/keycloak/src/main/fabric8/icon.svg"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=keycloak&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "keycloak"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "keycloak"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            project: "keycloak"
            provider: "fabric8"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/keycloak/src/main/fabric8/icon.svg"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=keycloak&var-version=2.2.311"
              pod.alpha.kubernetes.io/init-containers: "[{\"image\":\"busybox\",\"imagePullPolicy\"\
                :\"IfNotPresent\",\"name\":\"init\",\"command\":[\"chmod\",\"777\",\"\
                /opt/jboss/keycloak/standalone/data\"],\"volumeMounts\":[{\"mountPath\"\
                :\"/opt/jboss/keycloak/standalone/data\",\"name\":\"keycloak-data\"}]}]"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "keycloak"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "KEYCLOAK_USER"
                value: "admin"
              - name: "KEYCLOAK_PASSWORD"
                value: "admin"
              image: "jboss/keycloak:2.2.0.Final"
              livenessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/auth"
                  port: 8080
                initialDelaySeconds: 60
                timeoutSeconds: 10
              name: "keycloak"
              ports: []
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/auth"
                  port: 8080
                initialDelaySeconds: 10
                timeoutSeconds: 10
              volumeMounts:
              - mountPath: "/opt/jboss/keycloak/standalone/data"
                name: "keycloak-data"
                readOnly: false
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - name: "keycloak-data"
              persistentVolumeClaim:
                claimName: "keycloak-data"
    parameters: []
