---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/orion/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    maven.fabric8.io/app-catalog: "true"
  labels:
    provider: fabric8
    project: social
    version: target
    expose: "true"
    group: io.fabric8.devops.apps
    kind: catalog
  name: catalog-social
data:
  catalog-social.yml: |
    ---
    apiVersion: "v1"
    kind: "Template"
    metadata:
      annotations:
        fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/orion/src/main/fabric8/icon.png"
        fabric8.io/git-branch: "release-v2.2.311"
      finalizers: []
      labels:
        provider: "fabric8"
        project: "social"
        version: "target"
        expose: "true"
        group: "io.fabric8.devops.apps"
      name: "social"
      ownerReferences: []
    labels: {}
    objects:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/app-menu: "development"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/orion/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "orion"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
          expose: "true"
        name: "orion"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 80
          protocol: "TCP"
          targetPort: 8080
        selector:
          project: "orion"
          provider: "fabric8"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/app-menu: "development"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "taiga"
          expose: "true"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "taiga"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 80
          targetPort: 80
        selector:
          provider: "fabric8"
          project: "taiga"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "Service"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "taiga"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "taiga-back"
        ownerReferences: []
      spec:
        deprecatedPublicIPs: []
        externalIPs: []
        loadBalancerSourceRanges: []
        ports:
        - port: 8000
          targetPort: 8000
        selector:
          provider: "fabric8"
          project: "taiga"
          group: "io.fabric8.devops.apps"
    - apiVersion: "v1"
      kind: "PersistentVolumeClaim"
      metadata:
        annotations:
        finalizers: []
        labels:
          provider: "fabric8"
          project: "taiga"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "taiga-data"
        ownerReferences: []
      spec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          limits: {}
          requests:
            storage: "100Mi"
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/orion/src/main/fabric8/icon.png"
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=orion&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "orion"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "orion"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "orion"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/orion/src/main/fabric8/icon.png"
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=orion&var-version=2.2.311"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "orion"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
              image: "fabric8/eclipse-orion:2.2.311"
              imagePullPolicy: "IfNotPresent"
              name: "orion"
              ports:
              - containerPort: 8080
                name: "http"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              volumeMounts: []
            imagePullSecrets: []
            nodeSelector: {}
            volumes: []
    - apiVersion: "extensions/v1beta1"
      kind: "Deployment"
      metadata:
        annotations:
          fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png"
          fabric8.io/git-branch: "release-v2.2.311"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=taiga&var-version=2.2.311"
        finalizers: []
        labels:
          provider: "fabric8"
          project: "taiga"
          version: "2.2.311"
          group: "io.fabric8.devops.apps"
        name: "taiga"
        ownerReferences: []
      spec:
        replicas: 1
        selector:
          matchExpressions: []
          matchLabels:
            provider: "fabric8"
            project: "taiga"
            group: "io.fabric8.devops.apps"
        template:
          metadata:
            annotations:
              fabric8.io/git-commit: "2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3"
              fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/taiga/src/main/fabric8/icon.png"
              fabric8.io/git-branch: "release-v2.2.311"
              fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=taiga&var-version=2.2.311"
              pod.alpha.kubernetes.io/init-containers: "[{\"image\":\"busybox\",\"imagePullPolicy\"\
                :\"IfNotPresent\",\"name\":\"init\",\"command\":[\"chmod\",\"777\",\"\
                /var/lib/postgresql/data/\"],\"volumeMounts\":[{\"mountPath\":\"/var/lib/postgresql/data/\"\
                ,\"name\":\"taiga-data\"}]}]"
            finalizers: []
            labels:
              provider: "fabric8"
              project: "taiga"
              version: "2.2.311"
              group: "io.fabric8.devops.apps"
            name: "taiga"
            ownerReferences: []
          spec:
            containers:
            - args: []
              command: []
              env:
              - name: "POSTGRES_PASSWORD"
                value: "password"
              - name: "POSTGRES_USER"
                value: "taiga"
              image: "postgres"
              name: "taiga-postgres"
              ports: []
              volumeMounts:
              - mountPath: "/var/lib/postgresql/data/"
                name: "taiga-data"
            - args: []
              command: []
              env:
              - name: "SECRET_KEY"
                value: "xyz"
              - name: "POSTGRES_PORT_5432_TCP_ADDR"
                value: "127.0.0.1"
              - name: "POSTGRES_ENV_POSTGRES_USER"
                value: "taiga"
              - name: "POSTGRES_ENV_POSTGRES_PASSWORD"
                value: "password"
              image: "fabric8/taiga-back:2.2.311"
              livenessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/"
                  port: 8000
                initialDelaySeconds: 120
                timeoutSeconds: 10
              name: "taiga-backend"
              ports:
              - containerPort: 8000
                name: "irdmi"
                protocol: "TCP"
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/"
                  port: 8000
                initialDelaySeconds: 20
                timeoutSeconds: 10
              volumeMounts:
              - mountPath: "/var/lib/postgresql/data"
                name: "taiga-data"
              - mountPath: "/usr/local/taiga/static"
                name: "taiga-static"
              - mountPath: "/usr/local/taiga/media"
                name: "taiga-media"
            - args: []
              command: []
              env: []
              image: "fabric8/taiga-front:2.2.311"
              livenessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/"
                  port: 80
                initialDelaySeconds: 120
                timeoutSeconds: 10
              name: "taiga-frontend"
              ports:
              - containerPort: 80
                name: "http"
                protocol: "TCP"
              readinessProbe:
                httpGet:
                  httpHeaders: []
                  path: "/"
                  port: 80
                initialDelaySeconds: 20
                timeoutSeconds: 10
              volumeMounts:
              - mountPath: "/var/lib/postgresql/data"
                name: "taiga-data"
              - mountPath: "/usr/local/taiga/static"
                name: "taiga-static"
              - mountPath: "/usr/local/taiga/media"
                name: "taiga-media"
            imagePullSecrets: []
            nodeSelector: {}
            volumes:
            - name: "taiga-data"
              persistentVolumeClaim:
                claimName: "taiga-data"
            - name: "taiga-static"
            - name: "taiga-media"
    parameters: []
