---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/configmapcontroller/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.311
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=configmapcontroller&var-version=2.2.311
  labels:
    provider: fabric8
    project: configmapcontroller
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: configmapcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      project: configmapcontroller
      provider: fabric8
      group: io.fabric8.devops.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/configmapcontroller/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.2.311
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=configmapcontroller&var-version=2.2.311
      labels:
        provider: fabric8
        project: configmapcontroller
        version: 2.2.311
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8/configmapcontroller:2.3.5
        name: configmapcontroller
      serviceAccountName: configmapcontroller
