---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    group: io.fabric8.devops.apps
    project: gogs
    repository: gogs
    scm: git
    version: 2.2.311
  name: default-gogs-git
  namespace: user-secrets-source-admin
data:
  password: UmVkSGF0JDE=
  username: Z29nc2FkbWlu
