---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg
    fabric8.io/git-commit: 95aff298eeca6fba8f6ade3a5dab742a0f3a4381
    fabric8.io/git-branch: release-v2.2.199
    fabric8.io/build-id: "5"
    fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/95aff298eeca6fba8f6ade3a5dab742a0f3a4381
    fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/5
  labels:
    provider: fabric8
    project: fabric8-console
    expose: "true"
    version: 2.2.199
    group: io.fabric8.apps
  name: fabric8
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    project: fabric8-console
    provider: fabric8
    expose: "true"
    group: io.fabric8.platform.console
