---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/app-menu: development
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/git-branch: release-v2.2.311
  labels:
    provider: fabric8
    project: gogs
    version: 2.2.311
    group: io.fabric8.devops.apps
    expose: "true"
  name: gogs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    project: gogs
    provider: fabric8
    group: io.fabric8.devops.apps
