---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: gogs
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/git-branch: release-v2.2.311
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gogs&var-version=2.2.311
  labels:
    provider: fabric8
    project: gogs
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: fabric8
      project: gogs
      group: io.fabric8.devops.apps
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png
        fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
        configmap.fabric8.io/update-on-change: gogs
        fabric8.io/git-branch: release-v2.2.311
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=gogs&var-version=2.2.311
        pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/app/gogs/data"],"volumeMounts":[{"mountPath":"/app/gogs/data","name":"gogs-data"}]}]'
      labels:
        provider: fabric8
        project: gogs
        version: 2.2.311
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: GOGS_SERVER__ROOT_URL
          valueFrom:
            configMapKeyRef:
              key: gogs-server--root-url
              name: gogs
        - name: ADMIN_USER_EMAIL
          valueFrom:
            configMapKeyRef:
              key: admin-user-email
              name: gogs
        - name: ADMIN_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: admin-user-password
              name: gogs
        - name: ADMIN_USER_CREATE
          value: "true"
        - name: GOGS_WEBHOOK__TASK_INTERVAL
          value: "true"
        - name: GOGS_WEBHOOK__SKIP_TLS_VERIFY
          value: "true"
        - name: ADMIN_USER_NAME
          valueFrom:
            configMapKeyRef:
              key: admin-user-name
              name: gogs
        - name: KUBERNETES_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              key: kubernetes-admin-user
              name: gogs
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: fabric8/gogs:v0.9.97
        imagePullPolicy: IfNotPresent
        name: gogs
        ports:
        - containerPort: 2222
          name: ssh
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: /app/gogs/data
          name: gogs-data
      serviceAccountName: gogs
      volumes:
      - name: gogs-data
        persistentVolumeClaim:
          claimName: gogs-data
