---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    project: jenkins
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: jenkins-master-ssh
data:
  idrsa: ""
type: fabric8.io/jenkins-master-ssh
