---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    project: jenkins
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: jenkins-release-gpg
data:
  trustdb.gpg: ""
  pubring.gpg: ""
  gpg.conf: ""
  secring.gpg: ""
type: fabric8.io/jenkins-release-gpg
