---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.jenkins/summary: '[Jenkins](http://jenkins-ci.org/) extendable open source
      continuous integration server'
    description: |-
      Jenkins CI is a leading open-source continuous integration server. Built with Java, it provides 985 plugins to support building and testing virtually any project.

      [http://jenkins-ci.org/](http://jenkins-ci.org/)
    fabric8.jenkins/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg
    fabric8.io/json-schema: |-
      {
        "type" : "object",
        "properties" : {
          "PIPELINE_ELASTICSEARCH_PROTOCOL" : {
            "type" : "string",
            "description" : "Protocol used to connect to elasticsearch",
            "default" : "http"
          },
          "JENKINS_GOGS_USER" : {
            "type" : "string",
            "description" : "The user name for Jenkins to login to Gogs",
            "default" : "gogsadmin"
          },
          "JENKINS_GOGS_PASSWORD" : {
            "type" : "string",
            "description" : "The password for Jenkins to login to Gogs",
            "default" : "RedHat$1"
          },
          "PIPELINE_ELASTICSEARCH_HOST" : {
            "type" : "string",
            "description" : "Elasticsearch hostname used for pipeline events",
            "default" : "elasticsearch"
          },
          "JENKINS_GOGS_EMAIL" : {
            "type" : "string",
            "description" : "The email address of the Jenkins user on Gogs",
            "default" : "gogsadmin@fabric8.local"
          }
        }
      }
  labels:
    provider: fabric8
    project: jenkins
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: jenkins
data:
  jenkins-gogs-email: gogsadmin@fabric8.local
  jenkins-gogs-password: RedHat$1
  jenkins-gogs-user: gogsadmin
  pipeline-elasticsearch-protocol: http
  pipeline-elasticsearch-host: elasticsearch
  project-version: 2.2.311
