---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    project: jenkins
    version: 2.2.311
    group: io.fabric8.devops.apps
  name: jenkins-git-ssh
data:
  ssh-key: ""
  ssh-key.pub: ""
type: fabric8.io/jenkins-git-ssh
