variable "access_key" {
  type    = string
  default = "${env("ALICLOUD_ACCESS_KEY")}"
}

variable "secret_key" {
  type    = string
  default = "${env("ALICLOUD_SECRET_KEY")}"
}

source "alicloud-ecs" "autogenerated_1" {
  access_key           = "${var.access_key}"
  image_name           = "packer_basic_002"
  instance_type        = "ecs.t6-c1m1.large"
  security_group_id    = "sg-2ze52dgp0qaym7ummry4"
  vpc_id               = "vpc-2zeafwou20df9llgjpf2f"
  vswitch_id           = "vsw-2zedzi5yinwr0hzfsrxn6"
  internet_charge_type = "PayByTraffic"
  io_optimized         = "true"
  region               = "cn-beijing"
  secret_key           = "${var.secret_key}"
  source_image         = "centos_7_05_64_20G_alibase_20181210.vhd"
  ssh_username         = "root"
}

build {
  sources = ["source.alicloud-ecs.autogenerated_1"]
  provisioner "shell" {
    expect_disconnect = false
    pause_before      = "20s"
    inline = [
      "sleep 30",
      "yum install -y python3 python3-pip",
      "pip3 install -U pip",
      "pip3 install ansible"
    ]
  }
}
